server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0-1之间，1表示全部采集
      probability: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sawyer.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机版
#      defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，默认30s
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，默认90s
    lease-expiration-duration-in-seconds: 2